#!/usr/bin/env bash
# Swap the running llama.cpp server to a different model from local-models.json.
#
# Usage:
#   ./scripts/swap-local-model.sh gemma-4-E4B-it-Q4_K_M
#   ./scripts/swap-local-model.sh gemma-4-E4B-it-Q4_K_M --extra="--n-gpu-layers 99"
#
# Writes .env.llama-cpp with LLAMA_CPP_HF_REPO/FILE + EXTRA_ARGS, then
# restarts the compose stack. llama-server's -hf flag auto-downloads the
# GGUF into the hf-cache volume on first use.

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CATALOG="$HERE/src/local-models.json"
ENVFILE="$HERE/.env.llama-cpp"
COMPOSE="$HERE/compose.llama-cpp.yml"

if [ $# -lt 1 ]; then
  echo "usage: $0 <catalog-id> [--extra='<llama-server flags>']" >&2
  echo "" >&2
  echo "Available ids:" >&2
  jq -r '.[] | "  \(.id)  (\(.tier)) — \(.notes)"' "$CATALOG" >&2
  exit 1
fi

ID="$1"; shift || true
EXTRA=""
for arg in "$@"; do
  case "$arg" in
    --extra=*) EXTRA="${arg#--extra=}" ;;
  esac
done

ENTRY=$(jq -r --arg id "$ID" '.[] | select(.id == $id)' "$CATALOG")
if [ -z "$ENTRY" ]; then
  echo "error: no entry '$ID' in $CATALOG" >&2
  exit 1
fi

HF_REPO=$(jq -r '.hf_repo' <<<"$ENTRY")
QUANT=$(jq -r '.quant' <<<"$ENTRY")
CTX=$(jq -r '.context_window' <<<"$ENTRY")
# Per-model llama.cpp flags from the catalog (e.g. tool-call-parser).
CATALOG_ARGS=$(jq -r '(.llama_cpp_args // []) | map(select(. != "--jinja")) | join(" ")' <<<"$ENTRY")

cat > "$ENVFILE" <<EOF
# Generated by scripts/swap-local-model.sh
LLAMA_CPP_HF_REPO=$HF_REPO
LLAMA_CPP_QUANT=$QUANT
LLAMA_CPP_CTX=$CTX
LLAMA_CPP_EXTRA_ARGS=$CATALOG_ARGS $EXTRA
EOF

echo "[swap] id=$ID repo=$HF_REPO quant=$QUANT ctx=$CTX extra='$CATALOG_ARGS $EXTRA'"
echo "[swap] restarting llama-cpp service..."
docker compose --env-file "$ENVFILE" -f "$COMPOSE" up -d --force-recreate llama-cpp
echo ""
echo "[swap] server at http://localhost:18080/v1"
echo "[swap] to run tests against this model:"
echo "  LOCAL_LLM_BASE_URL=http://localhost:18080/v1 LOCAL_LLM_MODEL=$ID npx tsx src/run.ts --provider=local --all"
